const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const runtime = process.env.CODEX_NODE_MODULES || 'C:/Users/86178/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium} = require(path.join(runtime, 'playwright'));
const entry = path.join(__dirname, 'index.html');
const output = path.join(__dirname, 'verification');

(async () => {
  assert.ok(fs.existsSync(entry), 'HTML prototype is not implemented');
  fs.mkdirSync(output, {recursive: true});
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  const context = await browser.newContext({viewport: {width: 1320, height: 880}});
  const page = await context.newPage();
  await page.emulateMedia({reducedMotion: 'reduce'});
  const errors = [];
  const external = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', request => {if (/^https?:/.test(request.url())) external.push(request.url());});
  page.on('requestfailed', request => errors.push(`${request.url()}: ${request.failure()?.errorText}`));
  await context.route(/^https?:/, route => route.abort());
  await page.goto(pathToFileURL(entry).href);
  await page.getByRole('heading', {name: '消息群发', exact: true}).waitFor();
  await page.locator('#sidebar-toggle').click();
  assert.equal(await page.locator('.app').getAttribute('data-sidebar'), 'collapsed');
  await page.locator('#sidebar-toggle').click();
  await page.locator('#recipients').fill('演示同学甲\n演示同学乙\n演示同学丙');
  await page.locator('#message-template').fill('{name}，你好。');
  assert.ok((await page.locator('#message-preview').innerText()).includes('演示同学甲，你好。'));
  await page.locator('#recipients').click({button: 'right'});
  await page.locator('#context-menu').waitFor({state: 'visible'});
  assert.ok((await page.locator('#context-menu').innerText()).includes('全选'));
  await page.keyboard.press('Escape');
  await page.locator('#preview-attachment-0').click();
  await page.locator('#image-dialog').waitFor({state: 'visible'});
  await page.keyboard.press('Escape');
  await page.screenshot({path: path.join(output, 'message-light-1320.png')});

  await page.locator('[data-workspace="friends"]').click();
  assert.equal(await page.locator('#friend-table tbody tr').count(), 200);
  assert.ok((await page.locator('#friend-selection-count').innerText()).includes('0 / 100'));
  await page.locator('#range-end').fill('5');
  await page.locator('#select-range').click();
  assert.equal(await page.locator('#friend-table tbody input[type=checkbox]:checked').count(), 5);
  await page.locator('#friend-table tbody tr').nth(7).click();
  assert.equal(await page.locator('#friend-table tbody input[type=checkbox]:checked').count(), 5);
  const editable = page.locator('#friend-table tbody tr').first().locator('[data-field="name"]');
  await editable.dblclick();
  await editable.locator('input').fill('新演示姓名');
  await page.keyboard.press('Enter');
  assert.ok((await editable.innerText()).includes('新演示姓名'));
  await page.locator('#range-end').fill('200');
  await page.locator('#select-range').click();
  assert.equal(await page.locator('#friend-table tbody input[type=checkbox]:checked').count(), 5);
  await page.screenshot({path: path.join(output, 'friends-light-1320.png')});

  await page.locator('#open-settings').click();
  await page.locator('[data-settings="friends"]').click();
  await page.locator('#friend-min').fill('30');
  await page.locator('#friend-min').press('Enter');
  assert.equal(await page.locator('#friend-max').inputValue(), '30');
  await page.locator('#friend-max').fill('40');
  await page.locator('#settings-done').click();
  await page.locator('#open-settings').click();
  assert.equal(await page.locator('#friend-min').inputValue(), '30');
  assert.equal(await page.locator('#friend-max').inputValue(), '40');
  await page.locator('#friend-max').fill('41');
  await page.keyboard.press('Escape');
  await page.locator('#open-settings').click();
  assert.equal(await page.locator('#friend-max').inputValue(), '41', 'Escape must save the currently focused interval input');
  await page.locator('#friend-max').fill('40');
  await page.locator('#friend-max').press('Enter');
  await page.locator('#default-greeting').click({button: 'right'});
  await page.locator('#context-menu').waitFor({state: 'visible'});
  assert.ok(await page.locator('#context-menu').evaluate(menu => {
    const r = menu.getBoundingClientRect();
    return menu.contains(document.elementFromPoint(r.x + 20, r.y + 20));
  }), 'context menu must be above a modal dialog');
  await page.keyboard.press('Escape');
  if (!(await page.locator('#settings-dialog').isVisible())) await page.locator('#open-settings').click();
  await page.waitForTimeout(180);
  await page.screenshot({path: path.join(output, 'settings-light-1320.png')});
  await page.locator('#settings-done').click();

  await page.locator('[data-workspace="contacts"]').click();
  await page.locator('#contact-search').fill('设计');
  assert.ok(await page.locator('#contact-table tbody tr[data-contact]').count() > 0);
  await page.locator('#export-contacts').click();
  await page.locator('#export-dialog').waitFor({state: 'visible'});
  await page.locator('#export-confirm').click();
  await page.locator('#contact-search').fill('');
  await page.screenshot({path: path.join(output, 'contacts-light-1320.png')});

  await page.locator('[data-workspace="message"]').click();
  await page.locator('#start-message').click();
  await page.locator('#task-monitor').waitFor({state: 'visible'});
  await page.locator('#pause-task').click();
  const elapsed = await page.locator('#elapsed-time').innerText();
  await page.waitForTimeout(1300);
  assert.equal(await page.locator('#elapsed-time').innerText(), elapsed);
  await page.locator('#open-settings').click();
  await page.locator('[data-settings="friends"]').click();
  assert.ok(await page.locator('#friend-min').isDisabled());
  await page.locator('#settings-done').click();
  await page.locator('#pause-task').click();
  await page.screenshot({path: path.join(output, 'monitor-light-1320.png')});
  await page.locator('#stop-task').click();
  await page.locator('#return-editor').click();
  await page.locator('[data-workspace="friends"]').click();
  await page.locator('#start-friends').click();
  await page.locator('#task-waiting').filter({hasText: '下一条将在'}).waitFor();
  assert.ok((await page.locator('#health-label').innerText()).includes('自动化执行中'));
  await page.locator('#pause-task').click();
  const friendElapsed = await page.locator('#elapsed-time').innerText();
  assert.notEqual(friendElapsed, '00:00:00');
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('#elapsed-time').innerText(), friendElapsed);
  await page.locator('#pause-task').click();
  await page.locator('#task-scenario').click();
  await page.locator('[data-scenario="risk"]').click();
  await page.locator('#return-editor').click();
  assert.equal(await page.locator('#friend-table tr.risk').count(), 1);
  assert.ok((await page.locator('#friend-current').innerText()).includes('频繁限制'));
  const cell = page.locator('#friend-table tbody tr').first().locator('[data-field="name"]');
  await cell.dblclick();
  await cell.locator('input').fill('不保存这次修改');
  await page.keyboard.press('Escape');
  assert.ok((await cell.innerText()).includes('新演示姓名'));
  await page.locator('[data-workspace="contacts"]').click();
  await page.locator('#read-contacts').click();
  await page.locator('[data-workspace="message"]').click();
  assert.ok(await page.locator('#start-message').isDisabled());
  await page.locator('[data-workspace="contacts"]').click();
  await page.locator('#cancel-read').click();
  await page.locator('#read-contacts').click();
  await page.locator('#contact-stage').filter({hasText: '联系人已载入'}).waitFor();
  assert.equal(await page.locator('#contact-table tbody tr').count(), 72);
  await page.evaluate(() => document.querySelector('#toast-region').replaceChildren());

  for (const theme of ['light', 'dark']) {
    await page.evaluate(theme => window.fugePreview.setTheme(theme), theme);
    for (const viewport of [{width: 960, height: 680}, {width: 1320, height: 880}]) {
      await page.setViewportSize(viewport);
      for (const workspace of ['message', 'friends', 'contacts']) {
        await page.locator(`[data-workspace="${workspace}"]`).click();
        await page.screenshot({path: path.join(output, `${workspace}-${theme}-${viewport.width}.png`)});
        const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
        assert.equal(overflow, false, `${workspace}/${theme}/${viewport.width}: page overflow`);
        const bad = await page.locator('.workspace:not([hidden]) button').evaluateAll(buttons => buttons.filter(button => {
          const r = button.getBoundingClientRect();
          const scrollContainer = button.closest('.message-editor, .grid-scroll');
          return r.width && r.height && ((!scrollContainer && (r.right > innerWidth + 1 || r.bottom > innerHeight + 1)) || button.scrollWidth > button.clientWidth + 2);
        }).map(button => button.id || button.textContent.trim()));
        assert.deepEqual(bad, [], `clipped buttons in ${workspace}/${theme}/${viewport.width}`);
      }
    }
  }
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.locator('#open-settings').click();
  await page.locator('[data-settings="friends"]').click();
  assert.equal(await page.locator('#friend-min').inputValue(), '30');
  await page.locator('#settings-done').click();
  const hidpi = await browser.newContext({viewport: {width: 960, height: 680}, deviceScaleFactor: 1.5});
  const hidpiPage = await hidpi.newPage();
  await hidpiPage.goto(pathToFileURL(entry).href);
  await hidpiPage.screenshot({path: path.join(output, 'message-hidpi-150.png')});
  assert.deepEqual(errors, [], 'browser console/resource errors');
  assert.deepEqual(external, [], 'prototype must not use the network');
  await browser.close();
  console.log('PASS: offline load, navigation, preview, menus, range, editing, settings, contacts, task timing, responsive layouts and high DPI');
})().catch(error => {console.error(error); process.exit(1);});
